version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - orchestrator

  orchestrator:
    build:
      context: ./orchestrator-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LETTER_SERVICE_BASE_URL=http://letter-service:3003
      - NUMBER_SERVICE_BASE_URL=http://number-service:3004
      - SPECIAL_CHAR_SERVICE_URL=http://special-char-service:3005
      - IMAGE_COMPOSITOR_SERVICE_URL=http://compositor:3002
    depends_on:
      - compositor
      - letter-service
      - number-service
      - special-char-service

  compositor:
    build:
      context: ./image-compositor-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      
  letter-service:
    build:
      context: ./letter-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      
  number-service:
    build:
      context: ./number-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      
  special-char-service:
    build:
      context: ./special-char-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
