version: '3'

services:
  frontend:
    image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-frontend:0.4.2
    platform: linux/arm64/v8
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - orchestrator

  orchestrator:
    image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-orchestrator:0.4.2
    platform: linux/arm64/v8
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LOG_LEVEL=debug
      - LETTER_SERVICE_BASE_URL=http://letter-service:3000
      - NUMBER_SERVICE_BASE_URL=http://number-service:3000
      - SPECIAL_CHAR_SERVICE_URL=http://special-char-service:3000
      - IMAGE_COMPOSITOR_SERVICE_URL=http://compositor:3002
    depends_on:
      - compositor
      - letter-service
      - number-service
      - special-char-service

  compositor:
    build:
      context: ./image-compositor-service
      args:
        - PLATFORM=linux/arm64/v8
    platform: linux/arm64/v8
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - LOG_LEVEL=debug
      
  letter-service:
    image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-letter:0.4.2
    platform: linux/arm64/v8
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      
  number-service:
    image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-number:0.4.2
    platform: linux/arm64/v8
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      
  special-char-service:
    image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-special:0.4.2
    platform: linux/arm64/v8
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
