version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - orchestrator

  orchestrator:
    build:
      context: ./orchestrator-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - COMPOSITOR_URL=http://compositor:3002
    depends_on:
      - compositor

  compositor:
    build:
      context: ./image-compositor-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
