apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml

namespace: letter-image-generator-prod

commonLabels:
  environment: prod

patches:
- path: replicas-patch.yaml

images:
- name: letter-image-generator-frontend
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/letter-image-generator-frontend
  newTag: latest
- name: letter-image-generator-orchestrator
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/letter-image-generator-orchestrator
  newTag: latest
- name: letter-image-generator-compositor
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/letter-image-generator-compositor
  newTag: latest
