apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml

namespace: letter-image-generator

labels:
- includeSelectors: true
  pairs:
    environment: prod

patches:
- path: replicas-patch.yaml

# Note: These image references need to be updated with actual values before deployment
# Run the update-images.sh script to replace these with your actual ECR repository URLs
images:
- name: letter-image-generator-frontend
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/letter-image-generator-frontend
  newTag: latest
- name: letter-image-generator-orchestrator
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/letter-image-generator-orchestrator
  newTag: latest
- name: letter-image-generator-compositor
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/letter-image-generator-compositor
  newTag: latest
