apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compositor
spec:
  replicas: 2
