apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: letter-image-generator

resources:
  - namespaces.yaml
  - service-account.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - orchestrator-service.yaml
  - orchestrator-deployment.yaml
  - compositor-service.yaml
  - compositor-deployment.yaml
  - letter-service-service.yaml
  - letter-service-deployment.yaml
  - number-service-service.yaml
  - number-service-deployment.yaml
  - special-char-service-service.yaml
  - special-char-service-deployment.yaml
  - hpa.yaml
  - hpa-character-services.yaml
  - ingress.yaml

images:
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-frontend
    newTag: 0.4.0
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-orchestrator
    newTag: 0.4.0
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-compositor
    newTag: 0.4.0
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-letter-service
    newTag: 0.4.0
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-number-service
    newTag: 0.4.0
  - name: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-special-char-service
    newTag: 0.4.0
