apiVersion: v1
kind: Service
metadata:
  name: letter-service
  namespace: letter-image-generator
spec:
  selector:
    app: letter-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
