apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
    app.kubernetes.io/part-of: letter-image-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
      app.kubernetes.io/part-of: letter-image-generator
  template:
    metadata:
      labels:
        app: orchestrator
        app.kubernetes.io/part-of: letter-image-generator
    spec:
      serviceAccountName: ecr-pull-sa
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: orchestrator
        image: 037495631109.dkr.ecr.eu-south-2.amazonaws.com/letter-image-generator-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: COMPOSITOR_URL
          value: "http://compositor:3002"
        - name: LETTER_SERVICE_URL
          value: "http://letter-service:3003"
        - name: NUMBER_SERVICE_URL
          value: "http://number-service:3004"
        - name: SPECIAL_CHAR_SERVICE_URL
          value: "http://special-char-service:3005"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
