apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letter-image-generator-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: orchestrator
            port:
              number: 3001
