apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: letter-image-generator

labels:
- includeSelectors: true
  pairs:
    environment: dev

patches:
- path: replicas-patch.yaml

images:
- name: letter-image-generator-frontend
  newName: localhost/letter-image-generator-frontend
  newTag: latest
- name: letter-image-generator-orchestrator
  newName: localhost/letter-image-generator-orchestrator
  newTag: latest
- name: letter-image-generator-compositor
  newName: localhost/letter-image-generator-compositor
  newTag: latest
