apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compositor
spec:
  replicas: 1
